### ISSUE TITLE
Rails 4.1.10 & Mocha 0.14.0 & Shoulda Callback Matchers 1.1.2

### ISSUE THREAD

**Issue by tbrammar** [beatrichartz/shoulda-callback-matchers#13]
I had trouble getting Mocha to work with Rails 4.1 and tracked it down to an issue with the Shoulda Callback Matchers gem and how it declares `Test::Unit::TestCase` class.

You can follow the discussion [there](https://github.com/freerange/mocha/issues/219) and how we resolved it, but it may help if you adapt the way to you declare `Test::Unit::TestCase` class to be a bit more specific.

**Comment by beatrichartz** [comment]
Thanks for reporting this, I included Mocha in the test setup and fixed the issue. Release `1.1.3` should work without workaround.
