### ISSUE TITLE
With Condition Not Working

### ISSUE THREAD

**Issue by andreasarnold02** [beatrichartz/shoulda-callback-matchers#16]
Hi

I tried this code and its not working
```
 it { is_expected.to validate_presence_of(:shorten).on(:create).if(:custom) }
```
 
It throwed this error
"undefined method `if' for <Shoulda::Matchers::ActiveModel::AllowValueMatcher:0x00000005d7dd40>"

My gem
- shoulda-callback-matchers (1.1.3)
- rspec-rails (3.3.3)

Is there something wrong with my code?

Thanks!

**Comment by beatrichartz** [comment]
`validate_presence_of` is a method on the shoulda-matchers gem, this is the shoulda-callback-matchers gem, which only deals with testing callback existence.

**Comment by andreasarnold02** [comment]
No i mean the condition (if or unless) are methods on shoulda matchers callback right?
I use shoulda matchers too.

I mean from the (if) or the condition is throwing me that error

**Comment by beatrichartz** [comment]
Yes, so `shoulda-matchers` does not have a chainable `if` or `unless`, so when you're using `shoulda-matchers` test matchers like `validate_presence_of` or other validation test matchers, `if` and `unless` won't be available.

This gem only exposes the `callback` chainable matcher - that means it provides only the matchers you write which begin with `it { is_expected.to callback`
